### PR TITLE
chore: added info btn and game rules. needs some work still

### PR DESCRIPTION
**Pull request by erishei**
- info button added in nav
- info text should probably be redone

### CODE REVIEW

**Review by IngridOrnum — APPROVED** [review]
Amazing, great work!

**Review by Fillschjbo — COMMENTED** [review]
Groundbreaking chore work! Great job!

**Review by Fillschjbo — APPROVED** [review]

**Review by julieoyen — APPROVED** [review]
Looks good!

**Review by annikenlys — APPROVED** [review]
Looks good to me! Well done, approved :)

**Pull request merged**
