### PR TITLE
fix: game mode menu page Improved Accessibility

### PR DESCRIPTION
**Pull request by annikenlys**
- Reorganized HTML elements to enhance semantic structure.
- Changed "div" to "nav" since it contains navigation link.
- Updated heading levels for improved hierarchy and accessibility/UX.
- Added aria-label attributes for navigation links to improve accessibility.
- Adjusted indentation and formatting for better readability.

### CODE REVIEW

**Review by IngridOrnum — APPROVED** [review]
Looks great! Good job 👏🏻

**Comment by Fillschjbo** [comment]
Awsome work Anniken! Looks geat!

**Review by Fillschjbo — COMMENTED** [review]
Awesome work!

**Review by erishei — APPROVED** [review]
Looks neat, have no comments.

**Review by julieoyen — APPROVED** [review]

**Pull request merged**
